SEED: 2023
START_EPOCH: 0
EPOCHS: 1000
LR: 1.0e-4
LR_STEP: 10000
LR_FACTOR: 0.1
RESUME: null #outputs/checkpoint_192_3071_0.0227_0.9687.pth #null
BATCH_SIZE_PER_GPU: 64
WORKERS: 4
PIN_MEM: True

LOG_DIR: logs
LOG_CONFIG: logging.conf

PRINT_FREQ: 100
SAVE_STEP_INTER: 10000
OUTPUT_DIR: './outputs'


CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True

DATASETS:
  train:
    label_file: '/home/cluo/workspace/projects/general_ocr/datasets/rec/train_real.txt'
    image_dir: '/home/cluo/workspace/datasets/'
  val:
    label_file: '/home/cluo/workspace/projects/general_ocr/datasets/rec/test_real.txt'
    image_dir: '/home/cluo/workspace/datasets/'
  test:
    label_file: ''
    image_dir: ''

MODEL:
  name: svtr
  in_channel: 1

  BACKBONE:
    name: MobileNetV1Enhance
    scale: 0.5

  NECK:
    name: RNN

  HEAD:
    name: CTC
    n_class: 8536 # len(alphabet)+1, [0,1,...8534,8535]

LOSS:
  name: CTCLoss
  
TRAIN:

TEST:

VALIDATION:
