GPUS: (0, )
OUTPUT_DIR: outputs
LOG_DIR: logs
WORKERS: 4
PRINT_FREQ: 10
LOG_CONFIG: logging.conf
SEED: 2023

CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true

DATASETS:
  NUM_CLASSES: 8525

MODEL:
  NAME: svtr
  IN_CHANNEL: 3

TRAIN:

TEST:

VALIDATION:
