SEED: 2023
START_EPOCH: 0
EPOCHS: 100
LR: 1e-4
LR_STEP: 10000
LR_FACTOR: 0.1
RESUME: null
BATCH_SIZE_PER_GPU: 4
WORKERS: 4
PIN_MEM: True

LOG_DIR: logs
LOG_CONFIG: logging.conf

PRINT_FREQ: 100
SAVE_STEP_INTER: 10000
OUTPUT_DIR: './outputs'


CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True

DATASETS:
  train:
    label_file: '/home/cluo/Workspace/Projects/general_ocr/datasets/rec/datas/test_real.txt'
    image_dir: '/media/cluo/0000B445000DC2201/t1/第一批/image_cut_for_labeling/'
  val:
    label_file: '/home/cluo/Workspace/Projects/general_ocr/datasets/rec/datas/val_real.txt'
    image_dir: '/media/cluo/0000B445000DC2201/t1/第一批/image_cut_for_labeling/'
  test:
    label_file: ''
    image_dir: ''

MODEL:
  name: svtr
  in_channel: 1

  BACKBONE:
    name: MobileNetV1Enhance
    scale: 0.5

  NECK:
    name: RNN

  HEAD:
    name: CTC
    n_class: 8536 # len(alphabet)+1, [0,1,...8534,8535]

LOSS:
  name: CTCLoss
  
TRAIN:

TEST:

VALIDATION:
